### DISCUSSION TITLE
Run cross builds in parallel to speed up CI checks

### DISCUSSION THREAD

**Discussion by joelim-work** [gokcehan/lf#1775] [Ideas]
Cross builds was introduced as part of the CI checks in #1298, to prevent changes from being merged if they caused problems on specific platforms (see #1294 for an example).

Currently this is implemented by [`xbuild.sh`](https://github.com/gokcehan/lf/blob/master/gen/xbuild.sh), which works fine but is slow because it only builds on one platform at a time. When PRs are submitted, the cross build process usually takes around 5 minutes to complete.

I recently thought of using a [matrix strategy](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) in GitHub Actions to run the cross builds in parallel. With this, the process can be shortened to around 1.5 minutes, at least from my testing. The changes would look something like this:

`.github/workflows/go.yml`:

```yaml
jobs:
  cross-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { os: android, arch: arm64 }
          - { os: darwin, arch: amd64 }
          - { os: darwin, arch: arm64 }
          - { os: dragonfly, arch: amd64 }
          - { os: freebsd, arch: "386" }
          - { os: freebsd, arch: amd64 }
          - { os: freebsd, arch: arm }
          - { os: illumos, arch: amd64 }
          - { os: linux, arch: "386" }
          - { os: linux, arch: amd64 }
          - { os: linux, arch: arm }
          - { os: linux, arch: arm64 }
          - { os: linux, arch: ppc64 }
          - { os: linux, arch: ppc64le }
          - { os: linux, arch: mips }
          - { os: linux, arch: mipsle }
          - { os: linux, arch: mips64 }
          - { os: linux, arch: mips64le }
          - { os: linux, arch: s390x }
          - { os: netbsd, arch: "386" }
          - { os: netbsd, arch: amd64 }
          - { os: netbsd, arch: arm }
          - { os: openbsd, arch: "386" }
          - { os: openbsd, arch: amd64 }
          - { os: openbsd, arch: arm }
          - { os: openbsd, arch: arm64 }
          - { os: solaris, arch: amd64 }
          - { os: windows, arch: "386" }
          - { os: windows, arch: amd64 }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.18"

      - name: Cross-compile on all supported platforms
        run: gen/build.sh
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
```
